/** Deliberately static third-party-like fixture. Website content is not application UI copy. */
export const demoPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Clawler Playground</title><style>
*{box-sizing:border-box}body{margin:0;background:#f9f8f4;color:#293731;font-family:system-ui,sans-serif;padding:30px 32px}nav{display:flex;justify-content:space-between;font-size:11px;color:#78857c;border-bottom:1px solid #e6e7df;padding-bottom:18px}nav strong{color:#364c3f;letter-spacing:2px;font-size:12px}header{padding:35px 0 25px}small{color:#a37b48;letter-spacing:2px;font-size:10px}h1{font-family:Georgia,serif;font-size:40px;letter-spacing:-1.5px;line-height:1.08;font-weight:400;margin:15px 0}p{font-size:12px;color:#889188;line-height:1.7;max-width:390px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{background:#fff;border:1px solid #e6e9e1;border-radius:9px;overflow:hidden}.art{height:83px;display:grid;place-items:center;background:#e9eee4}.card:nth-child(2) .art{background:#f0e9df}.card:nth-child(3) .art{background:#e6ecef}.shape{height:36px;width:36px;border:8px solid #7c9078;border-radius:10px;transform:rotate(-12deg)}.card:nth-child(2) .shape{border-color:#bba287;border-radius:50%;transform:none}.card:nth-child(3) .shape{border-color:#8fa8b7;transform:rotate(15deg)}.copy{padding:12px}h2{font-size:11px;font-weight:500;margin:0 0 8px}a{font-size:10px;color:#8c9c8a;text-decoration:none}footer{font-size:10px;color:#a2aaa1;margin-top:25px;display:flex;justify-content:space-between}
</style></head><body><nav><strong>FIELDNOTES</strong><span>THE LOCAL PLAYGROUND</span></nav>
<header><small>A SPACE TO EXPERIMENT</small><h1>Small scripts.<br>Useful results.</h1><p>A quiet place to try your first automation. Inspect this page, collect its content, and make something reusable.</p></header>
<div class="grid"><article class="card"><div class="art"><div class="shape"></div></div><div class="copy"><h2>Automation basics</h2><a href="https://example.com/automation">Explore guide →</a></div></article><article class="card"><div class="art"><div class="shape"></div></div><div class="copy"><h2>Reusable scripts</h2><a href="https://example.com/scripts">Explore library →</a></div></article><article class="card"><div class="art"><div class="shape"></div></div><div class="copy"><h2>Isolated profiles</h2><a href="https://example.com/profiles">Explore profiles →</a></div></article></div>
<footer><span>THREE IDEAS. ONE WORKSPACE.</span><span>LOCAL DEMO / 01</span></footer></body></html>`;
